engines:
  eslint:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: false
ratings:
  paths:
  - app/**/*
  - bin/**/*
exclude_paths:
  - dist/*
  - test/*
  - docs/*
  - project-files/*
