engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - javascript

ratings:
  paths:
  - app/**/*

exclude_paths:
  - bin/*
  - coverage/*
  - dist/*
  - docs/*
  - project-files/*
  - test/*
