sudo: false

language: node_js

node_js:
  - 4
  - 5
  - 6

cache:
  - node_modules

install:
  - npm install

script:
  - npm run travis

notifications:
  email: false

addons:
  code_climate:
    repo_token: 880fba2220123f5927f30af7906e236a617c9af9548d66db565b83c52a69a21b
