vvv:   true
debug: true
token:

author:
  name: Your Name
  email: your-email@example.com
  website: http://your-website.example.com

project:
  template:  blr
  multisite: false
  title:
  slug:
  url:

repo:
  create: false
  url:

plugin:
  scaffold: true
  name:
  slug:
  description:

theme:
  scaffold: true
  name:
  slug:
  description:

admin:
  user:  admin
  pass:  admin_password
  email: admin@localhost.dev

db:
  name:
  user:      wp
  pass:      wp
  host:      localhost
  root_user: root
  root_pass: root
  prefix:

secret:
  auth_key:
  secure_auth_key:
  logged_in_key:
  nonce_key:
  auth_salt:
  secure_auth_salt:
  logged_in_salt:
  nonce_salt:
