env: 'development'
project:
  title: 'New WP Project'
  slug:  ''
  url:   ''
repo:
  create: false,
  url:    'https://github.com/wesm87/sage'
plugin:
  scaffold: true
  name:     ''
  slug:     ''
theme:
  scaffold: true
  name:     ''
  slug:     ''
admin:
  username: 'admin'
  password: 'admin_password'
  email:    'admin@localhost.dev'
db:
  name:     ''
  user:     'wp'
  password: 'wp'
  host:     'localhost'
  prefix:   ''
secret:
  authKey:        ''
  secureAuthKey:  ''
  loggedInKey:    ''
  nonceKey:       ''
  authSalt:       ''
  secureAuthSalt: ''
  loggedInSalt:   ''
  nonceSalt:      ''
