env: 'development'

project:
  title: ''
  slug:  ''
  url:   ''

repo:
  create: false,
  url:    ''

plugin:
  scaffold: true
  name:     ''
  slug:     ''

theme:
  scaffold: true
  name:     ''
  slug:     ''

admin:
  user:     'admin'
  password: 'admin_password'
  email:    'admin@localhost.dev'

db:
  name:     ''
  user:     'wp'
  password: 'wp'
  host:     'localhost'
  prefix:   ''

secret:
  authKey:        ''
  secureAuthKey:  ''
  loggedInKey:    ''
  nonceKey:       ''
  authSalt:       ''
  secureAuthSalt: ''
  loggedInSalt:   ''
  nonceSalt:      ''
