env: development

vvv: true

token:

project:
  title:
  slug:
  url:

repo:
  create: false,
  url:

plugin:
  scaffold: true
  name:
  slug:

theme:
  scaffold: true
  name:
  slug:

admin:
  user:  admin
  pass:  admin_password
  email: admin@localhost.dev

db:
  name:
  user:     wp
  pass:     wp
  host:     localhost
  rootUser: root
  rootPass: root
  prefix:

secret:
  authKey:
  secureAuthKey:
  loggedInKey:
  nonceKey:
  authSalt:
  secureAuthSalt:
  loggedInSalt:
  nonceSalt:
